"""PDF Generation Service for Meeting Intelligence Agent.

Generates professional, executive-ready PDF reports containing:
- Meeting title, date, duration, and participant roster
- Executive short & detailed summary
- Action items table with owner, due date, priority, and status
- Key decisions log with context
"""

import io
from datetime import datetime, timezone
from typing import Any, Sequence

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas
from reportlab.platypus import (
    HRFlowable,
    KeepTogether,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)


class NumberedCanvas(canvas.Canvas):
    """Two-pass canvas to dynamically compute and draw total page count and running footers."""

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        self._saved_page_states: list[dict[str, Any]] = []

    def showPage(self) -> None:
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self) -> None:
        page_count = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(page_count)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count: int) -> None:
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#94A3B8"))

        # Running header on page 2+
        if self._pageNumber > 1:
            self.drawString(54, 11 * inch - 36, "Meeting Intelligence Report")
            self.setStrokeColor(colors.HexColor("#E2E8F0"))
            self.setLineWidth(0.5)
            self.line(54, 11 * inch - 42, 8.5 * inch - 54, 11 * inch - 42)

        # Running footer on all pages
        footer_text = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(8.5 * inch - 54, 32, footer_text)
        self.drawString(54, 32, "Confidential — Generated by Meeting Intelligence Agent")
        self.setStrokeColor(colors.HexColor("#E2E8F0"))
        self.setLineWidth(0.5)
        self.line(54, 44, 8.5 * inch - 54, 44)

        self.restoreState()


def _format_datetime(dt: Any) -> str:
    if isinstance(dt, datetime):
        return dt.strftime("%B %d, %Y at %I:%M %p UTC")
    if isinstance(dt, str):
        try:
            parsed = datetime.fromisoformat(dt.replace("Z", "+00:00"))
            return parsed.strftime("%B %d, %Y at %I:%M %p UTC")
        except Exception:
            return dt
    return "N/A"


def _priority_color(priority: str) -> str:
    p = (priority or "").lower()
    if p == "high":
        return "#DC2626"  # Red
    if p == "medium":
        return "#D97706"  # Amber
    return "#16A34A"      # Green


def _status_color(status_val: str) -> str:
    s = (status_val or "").lower()
    if s == "done":
        return "#16A34A"
    if s == "in_progress":
        return "#2563EB"
    return "#64748B"


def generate_meeting_pdf(
    meeting: Any,
    action_items: Sequence[Any] | None = None,
    decisions: Sequence[Any] | None = None,
    participants: Sequence[Any] | None = None,
) -> bytes:
    """Compile meeting intelligence data into a professional PDF document.

    Args:
        meeting: Meeting ORM model or object with title, short_summary, detailed_summary,
                 duration_minutes, created_at, audio_filename.
        action_items: List of ActionItem models/objects.
        decisions: List of Decision models/objects.
        participants: List of Participant models/objects.

    Returns:
        bytes: Raw PDF document bytes.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        leftMargin=54,
        rightMargin=54,
        topMargin=54,
        bottomMargin=54,
    )

    styles = getSampleStyleSheet()

    # Custom Typography Styles
    title_badge_style = ParagraphStyle(
        "TitleBadge",
        fontName="Helvetica-Bold",
        fontSize=9,
        leading=11,
        textColor=colors.HexColor("#4F46E5"),
        spaceAfter=4,
    )

    title_style = ParagraphStyle(
        "ReportTitle",
        fontName="Helvetica-Bold",
        fontSize=20,
        leading=24,
        textColor=colors.HexColor("#0F172A"),
        spaceAfter=12,
    )

    meta_label_style = ParagraphStyle(
        "MetaLabel",
        fontName="Helvetica-Bold",
        fontSize=8,
        leading=10,
        textColor=colors.HexColor("#64748B"),
    )

    meta_val_style = ParagraphStyle(
        "MetaValue",
        fontName="Helvetica",
        fontSize=9,
        leading=12,
        textColor=colors.HexColor("#1E293B"),
    )

    section_heading_style = ParagraphStyle(
        "SectionHeading",
        fontName="Helvetica-Bold",
        fontSize=12,
        leading=15,
        textColor=colors.HexColor("#0F172A"),
        spaceBefore=14,
        spaceAfter=6,
    )

    body_style = ParagraphStyle(
        "ReportBody",
        fontName="Helvetica",
        fontSize=9.5,
        leading=14,
        textColor=colors.HexColor("#334155"),
        spaceAfter=6,
    )

    summary_highlight_style = ParagraphStyle(
        "SummaryHighlight",
        fontName="Helvetica-Bold",
        fontSize=10,
        leading=14,
        textColor=colors.HexColor("#1E293B"),
        spaceAfter=6,
    )

    table_header_style = ParagraphStyle(
        "TableHeader",
        fontName="Helvetica-Bold",
        fontSize=8.5,
        leading=11,
        textColor=colors.white,
    )

    table_cell_style = ParagraphStyle(
        "TableCell",
        fontName="Helvetica",
        fontSize=8.5,
        leading=11,
        textColor=colors.HexColor("#1E293B"),
    )

    table_cell_bold = ParagraphStyle(
        "TableCellBold",
        fontName="Helvetica-Bold",
        fontSize=8.5,
        leading=11,
        textColor=colors.HexColor("#1E293B"),
    )

    story = []

    # 1. Header & Title
    story.append(Paragraph("MEETING INTELLIGENCE REPORT", title_badge_style))
    meeting_title = getattr(meeting, "title", "Untitled Meeting")
    story.append(Paragraph(meeting_title, title_style))

    # 2. Metadata Grid
    created_at_str = _format_datetime(getattr(meeting, "created_at", None))
    duration_min = getattr(meeting, "duration_minutes", 0)
    audio_file = getattr(meeting, "audio_filename", "N/A")

    # Format participants
    participant_names = []
    if participants:
        for p in participants:
            name = getattr(p, "name", "")
            email = getattr(p, "email", "")
            if name and email:
                participant_names.append(f"{name} ({email})")
            elif name:
                participant_names.append(name)
    participants_str = ", ".join(participant_names) if participant_names else "None recorded"

    meta_data = [
        [
            Paragraph("DATE & TIME", meta_label_style),
            Paragraph(created_at_str, meta_val_style),
            Paragraph("DURATION", meta_label_style),
            Paragraph(f"{duration_min} minutes", meta_val_style),
        ],
        [
            Paragraph("PARTICIPANTS", meta_label_style),
            Paragraph(participants_str, meta_val_style),
            Paragraph("AUDIO SOURCE", meta_label_style),
            Paragraph(audio_file, meta_val_style),
        ],
    ]

    meta_table = Table(
        meta_data,
        colWidths=[1.1 * inch, 2.7 * inch, 1.1 * inch, 2.1 * inch],
    )
    meta_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F8FAFC")),
            ("BOX", (0, 0), (-1, -1), 1, colors.HexColor("#E2E8F0")),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#EDF2F7")),
            ("TOPPADDING", (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ("RIGHTPADDING", (0, 0), (-1, -1), 8),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ])
    )
    story.append(meta_table)
    story.append(Spacer(1, 12))

    # 3. Executive Summary
    story.append(Paragraph("Executive Summary", section_heading_style))
    short_sum = getattr(meeting, "short_summary", "") or "No short summary available."
    detailed_sum = getattr(meeting, "detailed_summary", "") or ""

    summary_elements = [
        Paragraph(f"Key Takeaway: {short_sum}", summary_highlight_style),
    ]
    if detailed_sum:
        for para in detailed_sum.split("\n\n"):
            para_text = para.strip()
            if para_text:
                summary_elements.append(Paragraph(para_text, body_style))

    summary_table = Table([[summary_elements]], colWidths=[7.0 * inch])
    summary_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F8FAFC")),
            ("BOX", (0, 0), (-1, -1), 1, colors.HexColor("#E2E8F0")),
            ("LINELEFT", (0, 0), (0, -1), 3.5, colors.HexColor("#4F46E5")),
            ("TOPPADDING", (0, 0), (-1, -1), 8),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
            ("LEFTPADDING", (0, 0), (-1, -1), 10),
            ("RIGHTPADDING", (0, 0), (-1, -1), 10),
        ])
    )
    story.append(summary_table)
    story.append(Spacer(1, 12))

    # 4. Action Items & Deliverables
    items = list(action_items or [])
    story.append(Paragraph(f"Action Items & Deliverables ({len(items)})", section_heading_style))

    if items:
        action_table_data = [
            [
                Paragraph("Task Description", table_header_style),
                Paragraph("Owner", table_header_style),
                Paragraph("Due Date", table_header_style),
                Paragraph("Priority", table_header_style),
                Paragraph("Status", table_header_style),
            ]
        ]

        for item in items:
            desc = getattr(item, "description", "")
            owner = getattr(item, "owner", "Unassigned") or "Unassigned"
            due = getattr(item, "due_date", "TBD") or "TBD"
            priority = str(getattr(item, "priority", "medium") or "medium").capitalize()
            raw_status = str(getattr(item, "status", "open") or "open")
            status_label = raw_status.replace("_", " ").capitalize()

            p_color = _priority_color(priority)
            s_color = _status_color(raw_status)

            priority_html = f'<font color="{p_color}"><b>{priority}</b></font>'
            status_html = f'<font color="{s_color}"><b>{status_label}</b></font>'

            action_table_data.append([
                Paragraph(desc, table_cell_style),
                Paragraph(owner, table_cell_bold),
                Paragraph(due, table_cell_style),
                Paragraph(priority_html, table_cell_style),
                Paragraph(status_html, table_cell_style),
            ])

        col_widths = [2.7 * inch, 1.2 * inch, 1.0 * inch, 1.0 * inch, 1.1 * inch]
        action_table = Table(action_table_data, colWidths=col_widths, repeatRows=1)
        action_table.setStyle(
            TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1E293B")),
                ("BOTTOMPADDING", (0, 0), (-1, 0), 6),
                ("TOPPADDING", (0, 0), (-1, 0), 6),
                ("LEFTPADDING", (0, 0), (-1, -1), 6),
                ("RIGHTPADDING", (0, 0), (-1, -1), 6),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8FAFC")]),
            ])
        )
        story.append(action_table)
    else:
        story.append(Paragraph("No action items were identified in this meeting.", body_style))

    story.append(Spacer(1, 12))

    # 5. Key Decisions Log
    dec_list = list(decisions or [])
    story.append(Paragraph(f"Key Decisions Log ({len(dec_list)})", section_heading_style))

    if dec_list:
        decision_flowables = []
        for idx, dec in enumerate(dec_list, 1):
            desc = getattr(dec, "description", "")
            context = getattr(dec, "context", "")
            item_elements = [
                Paragraph(f"<b>{idx}. {desc}</b>", body_style),
            ]
            if context:
                ctx_style = ParagraphStyle(
                    f"DecisionCtx_{idx}",
                    fontName="Helvetica-Oblique",
                    fontSize=8.5,
                    leading=11,
                    textColor=colors.HexColor("#64748B"),
                    leftIndent=12,
                    spaceAfter=4,
                )
                item_elements.append(Paragraph(f"Context: {context}", ctx_style))

            decision_flowables.append(KeepTogether(item_elements))

        story.extend(decision_flowables)
    else:
        story.append(Paragraph("No explicit decisions were recorded in this meeting.", body_style))

    # Build document
    doc.build(story, canvasmaker=NumberedCanvas)
    return buffer.getvalue()
